### ISSUE TITLE
Hostnames Don't Match

### ISSUE THREAD

**Issue by nicgrayson** [elodina/exhibitor-mesos-framework#51]
When exhibitor comes up the config has the fqdn in the config. Exhibitor pulls the hostname here: https://github.com/Netflix/exhibitor/blob/master/exhibitor-core/src/main/java/com/netflix/exhibitor/core/Exhibitor.java#L107

That call is returns the short hostname which cause it to not find itself in the cluster's config.

I'm not sure if this is something done by the framework. Do you know what sets up the config in the parent zookeeper?

Thanks in advance and let me know if you need anymore information on this.

**Comment by nicgrayson** [comment]
I figured this out. I ended up changing the https://github.com/Netflix/exhibitor/blob/master/exhibitor-core/src/main/java/com/netflix/exhibitor/core/Exhibitor.java#L107 to: 
`return InetAddress.getLocalHost().getCanonicalHostName();`

**Comment by serejja** [comment]
Hey @nicgrayson, FYI I've just merged a PR with a somewhat fix to this issue:

https://github.com/elodina/exhibitor-mesos-framework/pull/52

Mesos cluster does not necessarily use FQDN for hostnames in offers, but Exhibitor always uses `InetAddress.getLocalHost().getHostName()`. This PR sends the value of `InetAddress.getLocalHost().getHostName()` to the scheduler back in status update (once the Exhibitor reports itself as running) and gets added to ensemble with this value. This way it doesn't matter what kind of values you have in offers (ips, fqdns, whatever) - should now work.
